#!/bin/sh

screener &
touchpad &
dunst &
setbg /home/dns/Pictures/wall/wallpapers-master/Landscapes/ &
xbacklight -set 30 &
remaps &
locker &
redshift &
slstatus 2>&1 >/dev/null &

#pidof -s openrc &&
#	pidof -s ! pidof -s pulseaudio >/dev/null 2>&1 &&
#	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
